name: Docker Image CI

on:
  repository_dispatch:
    types: [ my-event ]
jobs:

  myEvent:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: try to access event
      run: echo here I am
