name: Docker

on:
  repository_dispatch:
    branches: [ my-event ]

  # Run tests for any PRs.
  pull_request:
  push:
   
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: genepattern/github-actions-testing

jobs:  
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build_and_push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run:   |
          # REF_IN=${{ github.event.client_payload.ref }}

          REF_IN=release/tags/v3.9.11-rc.5-b250
        
          VERSION=${REF_IN#*/tags/}
          INSTALLER_URL=https://github.com/genepattern/genepattern-server/releases/download/${VERSION}/GPserver.bin
          echo Image name is ${IMAGE_NAME}:${VERSION}
          docker build --build-arg GP_INSTALLER=${INSTALLER_URL} -t ${IMAGE_NAME}:${VERSION}  .
          
          # TBD PUSH THE IMAGE INTO DOCKERHUB
          docker login -u liefeld -p ${{ secrets.Teds_dockerhub_token }}
          docker push ${IMAGE_NAME}:${VERSION}
          echo DONE
